name = "newsletter-worker"
main = "src/index.ts"
compatibility_date = "2024-02-08"

# Variable bindings. These are arbitrary, plain text strings (similar to environment variables)
# Variable bindings. These are arbitrary, plain text strings (similar to environment variables)
[vars]
ORIGIN_BASE_URL = "http://localhost:4321"
PUBLIC_NEWSLETTER_API_URL = "http://localhost:8787"

# Bind a D1 Database. D1 is a distributed SQL database for Cloudflare Workers
[[d1_databases]]
binding = "DB"
database_name = "newsletter-db"
database_id = "df0e4157-47a2-44b8-bd24-6f77cac2a8a5"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

# Bind another Worker service. Use this binding to call another Worker without network overhead.
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# Durable Object migrations.
# [[migrations]]
# tag = "v1"
# new_classes = ["MyDurableObject"]
